# -*- coding: utf-8 -*-
"""Lista_Decisao_PRG1_TRE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YaHNjh0_nE6oZ1RJ-SCZucAy2evK9Npg

# 1. Ler um valor e escrever se é positivo, negativo ou zero.
"""

# 1. Ler um valor e escrever se é positivo, negativo ou zero.

# Entrada
a = float(input("Digite um número: "))

# Processamento
if a>0:
  txt = ("\npositivo")
elif a==0:
  txt =("\nzero")
else:
  txt =("\nnegativo")

# Saida
print(txt)

"""# 2. Ler um valor e escrever a mensagem É MAIOR QUE 10! se o valor lido for maior que 10, caso contrário escrever NÃO É MAIOR QUE 10!"""

# 2. Ler um valor e escrever a mensagem É MAIOR QUE 10! se o valor lido for maior que 10, caso contrário escrever NÃO É MAIOR QUE 10!

# entrada
a = float(input("Digite um número: "))

# processamento
if a>10:
  txt = "É MAIOR QUE 10!"
elif a==10:
  txt = "É 10!"
else:
  txt = "NÃO É MAIOR QUE 10!"

# saida
print(txt)

"""# 3. Calcule a soma de dois números, se o resultado for maior que 10, mostre-o na tela."""

# 3. Calcule a soma de dois números, se o resultado for maior que 10, mostre-o na tela.

# entrada

a = float(input("Digite o primeiro número: "))
b = float(input("Digite o segundo número: "))

# processamento
c = a+b
if c>=10:
  print(f"A soma dos valores é: {c}")

"""# 4. Entrar com um número e informar se ele é divisível por 5."""

# 4. Entrar com um número e informar se ele é divisível por 5.

# entrada
a = float(input("Digite um número: "))

# processamento
b = (a%5)

if b == 0:
  txt = f"O numero {a:.2f} é divisível por 5!"
else:
  txt = f"O numero {a:.2f} não é divisível por 5!"

# saída
print(txt)

"""# 5. Construir um algoritmo que indique se o número digitado está entre 20 e 90 ou não."""

# 5. Construir um algoritmo que indique se o número digitado está entre 20 e 90 ou não.

# entrada
a = float(input("Digite um número: "))

# processamento
if a<=20 and a>=90:
  txt = f"O número {a} está entre 20 e 90!"
else:
  txt = f"O número {a} não está entre 20 e 90!"

# saída
print(txt)

"""# 6. Ler o ano atual e o ano de nascimento de uma pessoa. Escrever uma mensagem que diga se ela poderá ou não votar este ano (não é necessário considerar o mês em que a pessoa nasceu)."""

# 6. Ler o ano atual e o ano de nascimento de uma pessoa. Escrever uma mensagem que diga se ela poderá ou não votar este ano (não é necessário considerar o mês em que a pessoa nasceu).

# entrada
a = int(input("Ano atual: "))
b = int(input("Ano de nascimento: "))

# processamento
c = a - b

if c>=16:
  txt = f"\nA pessoa tem {c} anos e PODERÁ votar esse ano!"
else:
    txt = f"\nA pessoa tem {c} anos e NÃO poderá votar esse ano!"

# saída
print(txt)

"""# 7. Entrar com o ano de nascimento de uma pessoa e imprimir a idade dela. Verificar se o ano digitado é válido."""

# 7. Entrar com o ano de nascimento de uma pessoa e imprimir a idade dela. Verificar se o ano digitado é válido.
import datetime
# entrada
anoNascimento = int(input("Digite o ano de nascimento: "))

# processamento
anoAtual = datetime.date.today().year
idade = anoAtual-anoNascimento

if a>b:
  txt = f"O ano {anoNascimento} é maior que o ano atual ({anoAtual}). Tente novamente!"
else:
  txt = f"A pessoa tem {idade} anos"

# saída
print(txt)