# -*- coding: utf-8 -*-
"""lista_introducao_prg1_tre.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/mklamaral/e2da0503cd32004f7115b4618444d63d/lista_introducao_prg1_tre.ipynb

# 1. Faça um algoritmo que leia dois números e mostre o produto desses números.
"""

# Entrada
num1 = int(input("Entre com o primeiro número: "))
num2 = int(input("Entre com o segundo número: "))

# Processamento
produto = num1 * num2

# Saída
print("Produto = ", produto)

"""# 2. Faça um algoritmo que leia uma temperatura em graus Fahrenheit e converta e mostre em graus Centígrados."""

# Apresentação
print("Neste programa vamos converter °F em °C\n")
# Entrada
tempF = int(input("Insira a temperatura em Fahrenheit: "))

# Processamento
tempC = (tempF - 32) * 5 / 9

# Saída
print(tempF,"°F são",tempC,"°C")

"""# 3. Faça um algoritmo que leia uma certa quantidade de chuva em polegadas e escreva o equivalente em milímetros."""

# Entrada
chuvaP = int(input("Insira o valor da chuva em polegadas: "))

# Processamento
chuvaMm = chuvaP * 25.4

# Saída
print(chuvaP,"Polegadas de chuva são", chuvaMm,"Milímetros de chuva")

"""# 4. Faça um algoritmo que calcule o volume de uma lata de óleo. Escreva o resultado."""

# imports
import math

# entrada
raioL = float(input("Insira o RAIO da lata de óleo: "))
alturaL = float(input("Insira a ALTURA da lata de óleo: "))

# processamento
volumeL = (round(math.pi, 3)) * (pow(raioL,2)) * alturaL

# saída
print("O volume da lata de óleo é: ",volumeL)

"""# 5. Faça um algoritmo que leia as 3 notas de um aluno e calcule e escreva a média final deste aluno. Considerar que a média é ponderada e que o peso das notas é: 2,3 e 5, respectivamente."""

# entrada
n1 = float(input("Insira a primeira nota: "))
n2 = float(input("Insira a segunda nota: "))
n3 = float(input("Insira a terceira nota: "))

# processamento
mediaFP = ((n1*2)+(n2*3)+(n3*5))/(2+3+5)

# saída
print("A media final do aluno é:", mediaFP)

"""# 6. Faça um algoritmo que leia as coordenadas de dois pontos, P1 (x1, y1) e P2 (x2, y2) respectivamente, e calcule e escreva a distância entre eles."""

# imports
import math
# entrada
x1 = float(input("Insira o X do primeiro ponto: "))
y1 = float(input("Insira o Y do primeiro ponto: "))

x2 = float(input("Insira o X do segundo ponto: "))
y2 = float(input("Insira o Y do segundo ponto: "))

# processamento
distancia = math.sqrt(((x2-x1)**2)+((y2-y1)**2))

# saída
print("A distância entre o Ponto 1 e o Ponto 2 é: ", distancia)

"""# 7. Faça um algoritmo que leia os valores a, b, c, d, e, f, e calcule x e y."""

# entrada
a = float(input("Insira o valor de A: "))
b = float(input("Insira o valor de B: "))
c = float(input("Insira o valor de C: "))
d = float(input("Insira o valor de D: "))
e = float(input("Insira o valor de E: "))
f = float(input("Insira o valor de F: "))

# processamento
x = (c*e)-(b*f)/(a*e)-(b*d)
y = (a*f)-(c*d)/(a*e)-(b*d)

# saída

print("O X dessa equação linear é:", x,"\nO Y dessa equação linear é:",y)

"""# 8. O custo ao consumidor de um carro novo é a soma do custo de fábrica com a percentagem do distribuidor e dos impostos (aplicados ao custo de fábrica). Supondo que a percentagem do distribuidor seja de 28% e os impostos de 45%, escrever um algoritmo que leia o custo de fábrica de um carro e escreva o custo ao consumidor."""

# entrada
custo = float(input("Digite o preço de custo: "))
dist = float(0.28)
impo = float(0.45)

# processamento
preco = custo + ((custo*dist) + (custo*impo))

# saida
print("O preço final do carro é:", preco)

"""# 9. Faça um algoritmo que leia a idade de uma pessoa expressa em dias e mostre-a  expressa em anos, meses e dias.  

"""

# entrada
idade = int(input("Digite sua idade: "))

# processamento
idadeAno = idade * 1
idadeMes = idade * 12
idadeDia = idade * 365

# saida
if (idade < 2):
  print(f"Com {idade} ano você tem {idadeAno} ano, {idadeMes} meses e {idadeDia} dias de vida! ")
else:
  print(f"Com {idade} anos você tem {idadeAno} anos, {idadeMes} meses e {idadeDia} dias de vida! ")

"""# 10. Faça um algoritmo que leia o tempo de duração de um evento em uma fábrica  expressa em segundos e mostre-o expresso em horas, minutos e segundos.  

"""

# entrada
tempo = int(input("Digite o tempo de duração do evento em segundos: "))

# processamento
tempoSeg = tempo
tempoMin = tempo/60
tempoH = tempo/3600

# saida
print(f"{tempo}s são {tempoSeg}s, {tempoMin}min e {tempoH}h")

"""# 11. O governador acaba de liberar R$ 1.000.000.000,00 para construção de casas  populares. Cada casa custa o equivalente a 90 salários mínimos. Faça um algoritmo  que leia o valor do salário mínimo e calcule a quantidade de casas que podem ser  construídas com o recurso liberado.

"""

# entrada
salMin = float(input("Digite  valor do salario minimo atual: "))

# processamento
verba = 1000000000
casaPopular = salMin*90
casaConstruida = verba/casaPopular

# saida
print(f"Com a verba de R${verba:,.2f} e cada casa custando 90 salários mínimos ({salMin:.2f}) é possivel construir {casaConstruida:.0f} casas")

"""# 12. Faça um algoritmo que leia o salário bruto mensal de um funcionário, calcule e  mostre os valores conforme modelo abaixo:  
Salário Bruto :R$  
(-) IR (15%) :R$  
(-) INSS (11%) :R$  
(-) Sindicato (3%) :R$  
Salário Líquido :R$

"""

# entrada
salBruto = float(input("Digite o salário bruto do funcionário: "))

# processamento
ir = 0.15
inss = 0.11
sindicato = 0.03
descontos = (salBruto*ir)+(salBruto*inss)+(salBruto*sindicato)
salLiquido = salBruto - descontos

# saida
print(f"\nSalário Bruto: R${salBruto:.2f}\nIR (15%): R${(salBruto*ir):.2f}\nINSS (11%): R${(salBruto*inss):.2f}\nSindicato: R${(salBruto*sindicato):.2f}\n=================================\nSalário Líquido: R${salLiquido:.2f}")

"""# 13. Maria quer saber quantos litros de gasolina precisa colocar em seu carro e quanto  vai gastar para fazer uma viagem até a casa de sua irmã. Faça um algoritmo que  leia:
• A distância da casa de Maria até sua irmã;  
• O consumo do carro de Maria (KM rodados / litro);  
• O preço da gasolina (litro).  
E mostre as informações que Maria necessita.

"""

# entrada
distancia = float(input("Digite a distância em KM: "))
consumo = float(input("Digite o KM rodado com 1 litro de combustivel: "))
preco = float(input("Digite o preço atual do combustível escolhido: "))

# processamento
litros = distancia/consumo
gasto = litros*preco

# saida
print(f"\nDistância: {distancia}km\nConsumo: {consumo:.1f}km/L\nPreço do combustível: R${preco:.2f}\n\nSerá preciso {litros:.2f}L de combustível e será gasto R${gasto:.2f}")

"""# 14. Faça um algoritmo que leia as medidas dos 4 lados de um terreno, o preço de um  mourão e o preço de um metro de arame farpado. Deve ser escrito:
• o número de mourões necessários para cercar o terreno, colocando um mourão a  cada 3 metros;
• o gasto total, o gasto em mourões e o gasto em arame, supondo que a cerca seja  feita com 4 fios de arame.

"""

# entrada
l1 = float(input("Digite a medida do lado 1 em metros: "))
l2 = float(input("Digite a medida do lado 2 em metros: "))
l3 = float(input("Digite a medida do lado 3 em metros: "))
l4 = float(input("Digite a medida do lado 4 em metros: "))

precoMourao = float(input("Digite o preço de um mourão: "))
precoArame = float(input("Digite o preço de um metro de arame farpado: "))

# processamento
perimetro = (l1+l2+l3+l4)
mouroes = (perimetro/3)+1
arames = (mouroes*4)*3

gastoMouroes = precoMourao*mouroes
gastoArames = (precoArame * arames)

# saida
print(f"Para um perimetro de {perimetro}m é necessário {mouroes:.2f} mourões e {arames:.2f}m de arames\n\nGasto em mourões: R${gastoMouroes:.2f}\nGasto em arames:R${gastoArames:.2f}\n\nGasto total: R${(gastoArames+gastoMouroes):.2f}")

"""# 15. São dados de entrada sobre um automóvel: modelo, marca, ano, km inicial, km final, litros de combustível consumidos, preço por litro. Faça um algoritmo que escreva os dados de saída da seguinte forma:
modelo_______________________ marca______________
ano________ distância percorrida ________________
litros de combustível consumidos _____________
preço por litro R$ _____________
total a pagar R$ ______________
km por litro __________
"""

#imports
from IPython.core.display import clear_output

# entrada
modelo = input("Digite o modelo do automóvel: ")
marca = input("Digite a marca do automóvel: ")
ano = input("Digite o ano do automóvel: ")
kmInicial = float(input("Digite o KM inicial:"))
kmFinal = float(input("Digite o KM final:"))
lConsumido = float(input("Digite o litro de combustível consumido: "))
pLitro = float(input("Digite o preço do litro de combustível: "))

# processamento
dPercorrida = kmFinal - kmInicial
kmLitro = dPercorrida/lConsumido
totalPagar = pLitro*lConsumido

# saida
clear_output()
print(f"Modelo: {modelo}\nMarca: {marca}\nAno: {ano}\nDistância percorrida: {dPercorrida}\nLitros de combustível consumidos: {lConsumido}\nPreço por litro: R${pLitro:.2f}\nTotal a pagar: R${totalPagar:.2f}\nKm por litro: {kmLitro:.1f}km/L")